services:
  nexus-tuner:
    container_name: nexus-tuner
    image: ghcr.io/fahmula/nexus-tuner:latest
    restart: unless-stopped

    # These variables override the defaults and ones in the .env file.
    # NEXUS_PORT changes the internal port the application listens on.
    environment:
      - NEXUS_PORT=4040
  
    # The application inside the container runs on port NEXUS_PORT (default 4040).
    # You can change 4040 to any other available port on your host (e.g., "1234:1234").
    # NOTE: The internal and external ports must match since clients will be served urls with NEXUS_PORT
    ports:
      - 4040:4040

    volumes:
      # By default the image uses /config as the NEXUS_CONFIG_DIR.
      # Point this to a folder on your host to persist configuration.
      - /path/to/config/folder/nexus-tuner:/config