# pyproject.toml

[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "nexus-tuner"
version = "0.0.1"  # placeholder for local installation
license = "AGPL-3.0-or-later"
license-files = ["LICENSE"]

[tool.setuptools]
package-dir = {"" = "nexus_tuner"}